name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on:
    - self-hosted

    steps:
    - name: "Infrastructure init"
      run: echo "Done"
    - name: "Checkout code"
      uses: actions/checkout@v2
    - name: "Build Project"
      run: |
        cd scripts
        cmd /C Win-GenProjects19.bat
        cd ../
    - name: "Compile Project"
      run: "& \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe\" \"./DataGraphDataLoadTool.sln\" /p:Configuration=Test /p:Platform=x64"
    - name: "Run Tests"
      run: ./bin/Test-windows-x86_64/Tool/Tool.exe --integration-tests
    - name: "Infrastructure down"
      run: "& \"C:\\dockerFamily\\docker_compose.exe\""
